modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="italian_delight"
version="0.8"
displayName="Italian Delight"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="PurpZ_The_Great"
description='''
ever wanted to have more italian foods? this mod is just what you need!
'''

[[dependencies.italian_delight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




